/**
 * ROLES AND PERMISSIONS
 * To control page access and user permissions in centralized location.
 * Reference link: https://isamatov.com/react-permissions-and-roles/
 */

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRANCH_EXECUTIVE: 'BRANCH_EXECUTIVE',
  GREETER: 'GREETER',
  BM: 'BM',
  CM: 'CM',
  ABM: 'ABM',
  ACM: 'ACM',
  REGION_OFFICE_EXECUTIVE: 'REGION_OFFICE_EXECUTIVE',
  REGION_OFFICE_MANAGER: 'REGION_OFFICE_MANAGER',
  LOB_EXECUTIVE: 'LOB_EXECUTIVE',
  LOB_MANAGER: 'LOB_MANAGER',
}

export const ROLE_NAMES = {
  SUPER_ADMIN: 'super.admin',
  BRANCH_EXECUTIVE: 'branch.executive',
  GREETER: 'greeter',
  BM: 'bm',
  CM: 'cm',
  ABM: 'abm',
  ACM: 'acm',
  REGION_OFFICE_EXECUTIVE: 'region.office.executive',
  REGION_OFFICE_MANAGER: 'region.office.manager',
  LOB_EXECUTIVE: 'lob.executive',
  LOB_MANAGER: 'lob.manager',
}

export const SCOPES = {
  CREATE: 'CREATE',
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  VIEW: 'VIEW',
  PRINT: 'PRINT',
  SUBMIT_REQUEST: 'SUBMIT_REQUEST',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
}

export const PAGES = {
  LOGIN: 'LOGIN',
  DASHBOARD: 'DASHBOARD',
  APPOINTMENT: 'APPOINTMENT',
  BRANCH: 'BRANCH',
  CONTENT: 'CONTENT',
  HOLIDAY: 'HOLIDAY',
  PARAMETER: 'PARAMETER',
  SERVICE: 'SERVICE',
  USER: 'USER',
  PROFILE: 'PROFILE',
}

// Maker: A group scope that can Create/Edit/Cancel requests.
export const MAKER = [SCOPES.SUBMIT_REQUEST]

// Checker: A group scope that can approve/reject requests that the maker made.
export const CHECKER = [SCOPES.APPROVE, SCOPES.REJECT]

// Checker: A group scope that can do anything in the page.
export const FULL_ACCESS = [SCOPES.CREATE, SCOPES.EDIT, SCOPES.DELETE, SCOPES.VIEW, SCOPES.PRINT]
  .concat(CHECKER)
  .concat(MAKER)

export const DEFAULT_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: FULL_ACCESS,
  [ROLES.BRANCH_EXECUTIVE]: FULL_ACCESS,
  [ROLES.GREETER]: FULL_ACCESS,
  [ROLES.BM]: FULL_ACCESS,
  [ROLES.CM]: FULL_ACCESS,
  [ROLES.ABM]: FULL_ACCESS,
  [ROLES.ACM]: FULL_ACCESS,
  [ROLES.REGION_OFFICE_EXECUTIVE]: FULL_ACCESS,
  [ROLES.REGION_OFFICE_MANAGER]: FULL_ACCESS,
  [ROLES.LOB_EXECUTIVE]: FULL_ACCESS,
  [ROLES.LOB_MANAGER]: FULL_ACCESS,
}

export const PAGE_PERMISSIONS = {
  [PAGES.LOGIN]: DEFAULT_PERMISSIONS,
  [PAGES.PROFILE]: DEFAULT_PERMISSIONS,
  [PAGES.DASHBOARD]: DEFAULT_PERMISSIONS,
  [PAGES.APPOINTMENT]: {
    [ROLES.SUPER_ADMIN]: FULL_ACCESS,
    [ROLES.BRANCH_EXECUTIVE]: [SCOPES.VIEW, SCOPES.PRINT, SCOPES.EDIT],
    [ROLES.GREETER]: [SCOPES.VIEW, SCOPES.EDIT],
    [ROLES.BM]: [SCOPES.VIEW, SCOPES.EDIT],
    [ROLES.CM]: [SCOPES.VIEW, SCOPES.EDIT],
    [ROLES.ABM]: [SCOPES.VIEW, SCOPES.EDIT],
    [ROLES.ACM]: [SCOPES.VIEW, SCOPES.EDIT],
    [ROLES.REGION_OFFICE_EXECUTIVE]: [SCOPES.VIEW],
    [ROLES.REGION_OFFICE_MANAGER]: [SCOPES.VIEW],
    [ROLES.LOB_EXECUTIVE]: [SCOPES.VIEW],
    [ROLES.LOB_MANAGER]: [SCOPES.VIEW],
  },
  [PAGES.BRANCH]: {
    [ROLES.SUPER_ADMIN]: FULL_ACCESS,
    [ROLES.BRANCH_EXECUTIVE]: [SCOPES.VIEW],
    [ROLES.GREETER]: [SCOPES.VIEW],
    [ROLES.BM]: [SCOPES.VIEW],
    [ROLES.CM]: [SCOPES.VIEW],
    [ROLES.ABM]: [SCOPES.VIEW],
    [ROLES.ACM]: [SCOPES.VIEW],
    [ROLES.REGION_OFFICE_EXECUTIVE]: MAKER,
    [ROLES.REGION_OFFICE_MANAGER]: CHECKER,
    [ROLES.LOB_EXECUTIVE]: MAKER,
    [ROLES.LOB_MANAGER]: CHECKER,
  },
  [PAGES.CONTENT]: {
    [ROLES.SUPER_ADMIN]: FULL_ACCESS,
    [ROLES.BRANCH_EXECUTIVE]: [SCOPES.VIEW],
    [ROLES.GREETER]: [SCOPES.VIEW],
    [ROLES.BM]: [SCOPES.VIEW],
    [ROLES.CM]: [SCOPES.VIEW],
    [ROLES.ABM]: [SCOPES.VIEW],
    [ROLES.ACM]: [SCOPES.VIEW],
    [ROLES.REGION_OFFICE_EXECUTIVE]: MAKER,
    [ROLES.REGION_OFFICE_MANAGER]: CHECKER,
    [ROLES.LOB_EXECUTIVE]: MAKER,
    [ROLES.LOB_MANAGER]: CHECKER,
  },
  [PAGES.HOLIDAY]: {
    [ROLES.SUPER_ADMIN]: FULL_ACCESS,
    [ROLES.BRANCH_EXECUTIVE]: [SCOPES.VIEW],
    [ROLES.GREETER]: [SCOPES.VIEW],
    [ROLES.BM]: [SCOPES.VIEW],
    [ROLES.CM]: [SCOPES.VIEW],
    [ROLES.ABM]: [SCOPES.VIEW],
    [ROLES.ACM]: [SCOPES.VIEW],
    [ROLES.REGION_OFFICE_EXECUTIVE]: MAKER,
    [ROLES.REGION_OFFICE_MANAGER]: CHECKER,
    [ROLES.LOB_EXECUTIVE]: MAKER,
    [ROLES.LOB_MANAGER]: CHECKER,
  },
  [PAGES.PARAMETER]: {
    [ROLES.SUPER_ADMIN]: FULL_ACCESS,
    [ROLES.BRANCH_EXECUTIVE]: [],
    [ROLES.GREETER]: [],
    [ROLES.BM]: [],
    [ROLES.CM]: [],
    [ROLES.ABM]: [],
    [ROLES.ACM]: [],
    [ROLES.REGION_OFFICE_EXECUTIVE]: [],
    [ROLES.REGION_OFFICE_MANAGER]: [],
    [ROLES.LOB_EXECUTIVE]: MAKER,
    [ROLES.LOB_MANAGER]: CHECKER,
  },
  [PAGES.SERVICE]: {
    [ROLES.SUPER_ADMIN]: FULL_ACCESS,
    [ROLES.BRANCH_EXECUTIVE]: [SCOPES.VIEW],
    [ROLES.GREETER]: [SCOPES.VIEW],
    [ROLES.BM]: [SCOPES.VIEW],
    [ROLES.CM]: [SCOPES.VIEW],
    [ROLES.ABM]: [SCOPES.VIEW],
    [ROLES.ACM]: [SCOPES.VIEW],
    [ROLES.REGION_OFFICE_EXECUTIVE]: [SCOPES.VIEW],
    [ROLES.REGION_OFFICE_MANAGER]: [SCOPES.VIEW],
    [ROLES.LOB_EXECUTIVE]: MAKER,
    [ROLES.LOB_MANAGER]: CHECKER,
  },
  [PAGES.USER]: {
    [ROLES.SUPER_ADMIN]: FULL_ACCESS,
    [ROLES.BRANCH_EXECUTIVE]: MAKER,
    [ROLES.GREETER]: MAKER,
    [ROLES.BM]: CHECKER,
    [ROLES.CM]: CHECKER,
    [ROLES.ABM]: CHECKER,
    [ROLES.ACM]: CHECKER,
    [ROLES.REGION_OFFICE_EXECUTIVE]: MAKER,
    [ROLES.REGION_OFFICE_MANAGER]: CHECKER,
    [ROLES.LOB_EXECUTIVE]: MAKER,
    [ROLES.LOB_MANAGER]: CHECKER,
  },
}
