---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
spec:
  type: team
  children: [developer]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developer
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tkhenghong
spec:
  profile:
    displayName: Teoh Kheng Hong
    email: tkhenghong.maybank@gmail.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [developer]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: md.saad
spec:
  profile:
    displayName: Mohammad Saad
    email: mdsa3d@gmail.com
    picture: https://avatars.githubusercontent.com/u/75714714?v=4
  memberOf: [developer]
